In [4]:
import numpy as np
npp=np.nan

In [6]:
type(npp)

float

# HOW TO CREATE BASIC ARRAY

# 1D ARRAY

In [13]:
import numpy as np
npp=np.nan

In [15]:
arr1=np.array([1,2,3,4,5,6,7])
print(arr1)

[1 2 3 4 5 6 7]


In [17]:
arr1=np.array([10,20,30,40,50])
arr1

array([10, 20, 30, 40, 50])

# 2D ARRAY

In [39]:
arr2=np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# 3D ARRAY

In [135]:
arr3=np.array([[[1,2,3,4], [5,6,7,8]], [[9,10,11,12],[12,13,14,15]]])
print(arr3)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [12 13 14 15]]]


# adding a single element

In [52]:
arr=np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [72]:
arr=np.array([10,20,30,40,50, 'tinu'])
arr

array(['10', '20', '30', '40', '50', 'tinu'], dtype='<U11')

In [56]:
new_arr=np.append(arr,60)
new_arr

array([10, 20, 30, 40, 50, 60])

# adding multiple element

In [58]:
new_arr=np.append(arr,[70,80,90])
new_arr

array([10, 20, 30, 40, 50, 70, 80, 90])

# adding to a specific index

In [62]:
new_arr=np.insert(arr,1,15)
new_arr

array([10, 15, 20, 30, 40, 50])

# removing elements from an array

In [69]:
new_arr=np.delete(arr,2)
new_arr

array([10, 20, 40, 50])

# sorting an array

# sorting numbers

In [80]:
arr=np.array([20,5,15,30,25,34,78,54,93,23,51,17,39])
arr

array([20,  5, 15, 30, 25, 34, 78, 54, 93, 23, 51, 17, 39])

In [82]:
sorted_arr=np.sort(arr)
sorted_arr

array([ 5, 15, 17, 20, 23, 25, 30, 34, 39, 51, 54, 78, 93])

# sorting strings

In [89]:
arr=np.array(['gum','apple','ball','yam','tinu'])
arr

array(['gum', 'apple', 'ball', 'yam', 'tinu'], dtype='<U5')

In [91]:
sorted_arr=np.sort(arr)
sorted_arr

array(['apple', 'ball', 'gum', 'tinu', 'yam'], dtype='<U5')

# sorting a 2D array

In [109]:
arr=np.array([[2,1,3,5,4], [10,8,4,3,2]])
arr

array([[ 2,  1,  3,  5,  4],
       [10,  8,  4,  3,  2]])

In [111]:
sorted_arr=np.sort(arr)
sorted_arr

array([[ 1,  2,  3,  4,  5],
       [ 2,  3,  4,  8, 10]])

# checking the shape and size of an array

# 1D

In [114]:
arr=np.array([20,5,15,30,25,34,78,54,93,23,51,17,39])
arr

array([20,  5, 15, 30, 25, 34, 78, 54, 93, 23, 51, 17, 39])

In [116]:
arr.shape

(13,)

# 2D

In [122]:
arr=np.array([[2,1,3], [10,8,4]])
arr

array([[ 2,  1,  3],
       [10,  8,  4]])

In [124]:
arr.shape

(2, 3)

# 3D

In [137]:
arr3=np.array([[[1,2,3,4], [5,6,7,8]], [[9,10,11,12],[12,13,14,15]]])
print(arr3)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [12 13 14 15]]]


In [139]:
arr.shape

(2, 3)

# checking the size of an array

In [143]:
arr=np.array([20,5,15,30,25,34,78,54,93,23,51,17,39])
arr

array([20,  5, 15, 30, 25, 34, 78, 54, 93, 23, 51, 17, 39])

In [145]:
arr.size

13

# reshaping an array

In [152]:
arr=np.array([20,5,15,30,25,34,78,54,93,23,51,17,39,16])
arr

array([20,  5, 15, 30, 25, 34, 78, 54, 93, 23, 51, 17, 39, 16])

In [160]:
arr.reshape(7,2)

array([[20,  5],
       [15, 30],
       [25, 34],
       [78, 54],
       [93, 23],
       [51, 17],
       [39, 16]])

In [170]:
arr=np.array([20,5,15,30,25,34,78,54,93,23,51,17,39,16,87,45,23,78,56,12,13,15,17,18,19,76,54])
arr

array([20,  5, 15, 30, 25, 34, 78, 54, 93, 23, 51, 17, 39, 16, 87, 45, 23,
       78, 56, 12, 13, 15, 17, 18, 19, 76, 54])

In [177]:
arr.reshape(3,3,3)

array([[[20,  5, 15],
        [30, 25, 34],
        [78, 54, 93]],

       [[23, 51, 17],
        [39, 16, 87],
        [45, 23, 78]],

       [[56, 12, 13],
        [15, 17, 18],
        [19, 76, 54]]])

# convert a 1D array into 2D

In [183]:
arr=np.array([20,5,15,30,25,34,78,54,93,23,51,17,39,16,87,45,23,78,56,12,13,15,17,18,19,76])
arr

array([20,  5, 15, 30, 25, 34, 78, 54, 93, 23, 51, 17, 39, 16, 87, 45, 23,
       78, 56, 12, 13, 15, 17, 18, 19, 76])

In [185]:
arr.reshape(13,2)

array([[20,  5],
       [15, 30],
       [25, 34],
       [78, 54],
       [93, 23],
       [51, 17],
       [39, 16],
       [87, 45],
       [23, 78],
       [56, 12],
       [13, 15],
       [17, 18],
       [19, 76]])

In [187]:
arr=np.array([20,5,15,30,25,34,78,54,93,23,51,17,39,16,87,45,23,78,56,12])
arr

array([20,  5, 15, 30, 25, 34, 78, 54, 93, 23, 51, 17, 39, 16, 87, 45, 23,
       78, 56, 12])

In [189]:
arr.reshape(5,4)

array([[20,  5, 15, 30],
       [25, 34, 78, 54],
       [93, 23, 51, 17],
       [39, 16, 87, 45],
       [23, 78, 56, 12]])

# adding new axis to an array   (np.newaxis)

In [5]:
import numpy as np

In [7]:
arr=np.array([1,2,3,4,5,6])
new_arr=arr[:,np.newaxis]
new_arr

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [195]:
arr=np.array([1,2,3,4,5,6])
new_arr=arr[np.newaxis,:]
new_arr

array([[1, 2, 3, 4, 5, 6]])

# using .reshape to add new axis

In [11]:
arr=np.array([1,2,3,4,5,6])
new_arr=arr.reshape(-1,1)
new_arr

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# 2D TO 3D ARRAY

In [16]:
arr=np.array([[1,2], [3,4], [5,6]])
new_arr=arr[:, :, np.newaxis]
new_arr

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

# NUMPY INDEXING

# indexing in 1d array

In [20]:
import numpy as np

In [22]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19])

In [24]:
arr[0]

1

In [26]:
arr[1]

2

In [28]:
arr[5]

6

In [30]:
arr[-1]

19

In [32]:
arr[-18]

2

In [34]:
arr[-6]

14

In [36]:
arr[-7]

13

In [38]:
arr[18]

19

In [40]:
arr[19]

IndexError: index 19 is out of bounds for axis 0 with size 19

# indexing in 2D array

In [59]:
import numpy as np

In [61]:
arr=np.array([[5,10,15],
              [20,25,30],
              [35,40,45]])

# accessing a single element

# forward indexing

In [64]:
arr[0,1]

10

In [66]:
arr[1,2]

30

In [70]:
arr[2,2]

45

# backward indexing

In [72]:
arr[-1,1]

40

In [74]:
arr[-1,-3]

35

In [76]:
arr[-2,-3]

20

In [78]:
arr[-3,-2]

10

# extracting an entire row

# forward indexing

In [81]:
arr[1,:]

array([20, 25, 30])

In [83]:
arr[0,:]

array([ 5, 10, 15])

In [85]:
arr[2,:]

array([35, 40, 45])

# backward indexing

In [87]:
arr[-1,:]

array([35, 40, 45])

In [93]:
arr[-3,:]

array([ 5, 10, 15])

In [95]:
arr[-2,:]

array([20, 25, 30])

In [97]:
arr[-4,:]

IndexError: index -4 is out of bounds for axis 0 with size 3

# extracting an entire column

# forward indexing

In [100]:
arr[:,0]

array([ 5, 20, 35])

In [103]:
arr[:,1]

array([10, 25, 40])

In [105]:
arr[:,2]

array([15, 30, 45])

# backward indexing

In [108]:
arr[:,-3]

array([ 5, 20, 35])

In [110]:
arr[:,-2]

array([10, 25, 40])

In [112]:
arr[:,-1]

array([15, 30, 45])

# selecting multiple element

In [115]:
arr[[0,2],[1,2]]

array([10, 45])

In [119]:
arr[[1,0],[2,1]]

array([30, 10])

In [124]:
arr[[0,2],[2,0]]

array([15, 35])

# slicing

In [127]:
import numpy as np

In [129]:
arr=np.array([[5,10,15],
              [20,25,30],
              [35,40,45]])

# extracting a submatrix

In [133]:
arr[0:2,1:3]

array([[10, 15],
       [25, 30]])

# selecting an entire rows or column

# rows

In [136]:
arr[1,:]

array([20, 25, 30])

In [138]:
arr[-1,:]

array([35, 40, 45])

In [ ]:
a

# column

In [142]:
arr[:,1]

array([10, 25, 40])

In [144]:
arr[:,-2]

array([10, 25, 40])

# step slicing

In [147]:
arr[::2,::2]

array([[ 5, 15],
       [35, 45]])

In [149]:
arr[::-2,::-1]

array([[45, 40, 35],
       [15, 10,  5]])

# create an array from existing array

# using slicing

In [154]:
import numpy as np

In [164]:
arr=np.array([[5,10,15],
              [20,25,30],
              [35,40,45]])

In [168]:
arr[0:2,1:3]

array([[10, 15],
       [25, 30]])

# using .copy

In [173]:
arr[:,1:].copy()

array([[10, 15],
       [25, 30],
       [40, 45]])

# using fancy indexing

In [176]:
arr[[0,2],[1,2]]

array([10, 45])

In [183]:
arr[[1,0],[2,2]]

array([30, 15])

# using np.where

In [179]:
arr[arr>20]

array([25, 30, 35, 40, 45])

In [185]:
arr[arr>30]

array([35, 40, 45])

# basic array operations

In [188]:
import numpy as np

In [194]:
arr1=np.array([[1,2,3],
              [4,5,6]])
arr2=np.array([[10,20,30],
               [40,50,60]])

# addition

In [196]:
arr1+arr2

array([[11, 22, 33],
       [44, 55, 66]])

# subtraction 

In [200]:
arr1-arr2

array([[ -9, -18, -27],
       [-36, -45, -54]])

In [202]:
arr2-arr1

array([[ 9, 18, 27],
       [36, 45, 54]])

# multiplication 

In [205]:
arr1*arr2

array([[ 10,  40,  90],
       [160, 250, 360]])

# division

In [208]:
arr1/arr2

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

In [210]:
arr2/arr1

array([[10., 10., 10.],
       [10., 10., 10.]])

# power **

In [213]:
arr1**arr2

array([[          1,     1048576, -1010140999],
       [          0,  1296002393,           0]])

In [215]:
arr2**arr1

array([[        10,        400,      27000],
       [   2560000,  312500000, -588640256]])

# broadcasting ( single values)

In [231]:
arr1=np.array([[1,2,3],
              [4,5,6]])

# add a single value to the arrays

In [235]:
arr1+10

array([[11, 12, 13],
       [14, 15, 16]])

# subtract a value from the arrays

In [229]:
arr1-10

array([[-9, -8, -7],
       [-6, -5, -4]])

In [239]:
arr1-2

array([[-1,  0,  1],
       [ 2,  3,  4]])

# multiply

In [244]:
arr1*5

array([[ 5, 10, 15],
       [20, 25, 30]])

# division

In [247]:
arr1/3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [249]:
arr1/1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [251]:
arr1/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [253]:
# power **

In [255]:
arr1**6

array([[    1,    64,   729],
       [ 4096, 15625, 46656]], dtype=int32)

In [257]:
arr1**2

array([[ 1,  4,  9],
       [16, 25, 36]])

# aggregration functions ( sum,mean,min,max,etc)

# sum

In [263]:
arr.sum()

21

# mean

In [266]:
arr.mean()

3.5

# max

In [268]:
arr.max()

6

# min

In [270]:
arr.min()

1

# standard deviation

In [272]:
arr.std()

1.707825127659933

# comparison operations

# GREATER THAN

In [278]:
arr>3

array([[False, False, False],
       [ True,  True,  True]])

# LESS THAN

In [284]:
arr<3

array([[ True,  True, False],
       [False, False, False]])

# EQUAL TO

In [287]:
arr==5

array([[False, False, False],
       [False,  True, False]])

In [289]:
arr==3

array([[False, False,  True],
       [False, False, False]])

# logical operations &,|

In [ ]:
# just like the previous ones

# creating matrices in numpy

In [ ]:
# np.array()
# np.zeros()
# np.ones()
# np.eye()
# np.random functions

# np.array()

In [299]:
import numpy as np

In [352]:
np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# np.zeros()

In [350]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [368]:
np.zeros((4,4,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

# np.ones()

In [346]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# np.eye()

In [348]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [372]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# np.random()

In [396]:
np.random.random((3,3))  #float

array([[0.92836645, 0.33944418, 0.79429472],
       [0.19039651, 0.92095727, 0.35704376],
       [0.02787503, 0.34596881, 0.73052141]])

In [398]:
np.random.random((3,3))  #float

array([[0.4369566 , 0.60759717, 0.54114327],
       [0.30718106, 0.9290894 , 0.16717862],
       [0.13120626, 0.6396518 , 0.41619595]])

In [400]:
np.random.randint(0,10,(3,3))  #int

array([[4, 8, 9],
       [9, 8, 7],
       [5, 8, 8]])

In [402]:
np.random.randint(1,20,(3,3))  #int

array([[19, 10, 18],
       [14,  5,  5],
       [12,  7, 16]])

In [404]:
np.random.randint(1,2,(3,3))  #int

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

# Using unique items and counts

In [409]:
import numpy as np

In [411]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [413]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# finding unique items and count

In [427]:
np.unique(arr,return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64))

In [429]:
arr=np.array([1,2,2,2,3,4,4,5,5,6,7,8,8,9,9])

In [431]:
np.unique(arr,return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1, 3, 1, 2, 2, 1, 1, 2, 2], dtype=int64))

# transposing a matrix (.T OR np.transpose() )

In [443]:
arr=np.array([[5,10,15],
              [20,25,30]])

In [445]:
arr.T

array([[ 5, 20],
       [10, 25],
       [15, 30]])

In [449]:
np.transpose(arr)

array([[ 5, 20],
       [10, 25],
       [15, 30]])

# Reshaping a Matrix

In [467]:
arr=np.array([2,3,4,5,6,7,8,9,10,15])

In [479]:
arr.reshape(2,5)

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 15]])

In [485]:
arr=np.array([[2,3],
             [4,5],
             [6,7],
             [8,9],
             [10,15]])

In [487]:
arr.flatten()

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 15])

In [489]:
arr=np.array([[1,2],
              [3,4]])

In [491]:
arr.flatten()

array([1, 2, 3, 4])

# NUMPY + IMAGES